# Generated by Django 4.0.8 on 2025-02-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
